FROM docker.io/library/nginx:alpine

# Herramientas para cert y htpasswd
RUN apk add --no-cache openssl apache2-utils

# Directorios
RUN mkdir -p /etc/nginx/certs /etc/nginx/auth

# Certificado autofirmado (x.509)
RUN openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
  -subj "/C=ES/ST=Malaga/L=Malaga/O=UNIR/OU=DevOps/CN=cp2.local" \
  -keyout /etc/nginx/certs/server.key \
  -out /etc/nginx/certs/server.crt

# Usuario/contraseña para Basic Auth (cámbialo si quieres)
# user: unir / pass: devops2026
RUN htpasswd -bc /etc/nginx/auth/.htpasswd unir devops2026

# Copiamos contenido y config
COPY html/ /usr/share/nginx/html/
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443
