server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

#Lo comento para que se vea que el criterio 1 lo hice por https pero no lei que es opcional y
#es mas comodo por http. Dejo lo que hice para no perder el codigo

#server {
#  listen 443 ssl;
#  server_name _;

#  ssl_certificate     /etc/nginx/certs/server.crt;
#  ssl_certificate_key /etc/nginx/certs/server.key;

#  auth_basic "Restricted";
#  auth_basic_user_file /etc/nginx/auth/.htpasswd;

#  root /usr/share/nginx/html;
#  index index.html;

#  location / {
#    try_files $uri $uri/ =404;
#  }
#}

# Redirección HTTP -> HTTPS
#server {
#  listen 80;
#  server_name _;
#  return 301 https://$host$request_uri;
#}
